### PR TITLE
Add cartographic rendering mode

### LINKED ISSUE #18: Viewer: use geovista?
It would be nice to use geovista in the Pan3D viewer to show the datasets in a global context

ref https://github.com/pyvista/pyvista-xarray/blob/main/examples/level_of_detail_geovista.py

180887602-e1c71e32-8c0f-4cee-a587-ae9d226a571c

### PR DESCRIPTION
**Pull request by annehaley**
Resolves #18.

This PR adds a flag "render_cartographic" to the `DatasetViewer` state. When enabled, the current data will be rendered on the surface of a sphere with an earth texture. To accomplish this, we now use a `GeoPlotter` from the `geovista` library, which inherits from `pyvista.Plotter`. This PR adds `geovista` to the dependencies for the viewer.

The video below shows basic usage of the cartographic flag:
https://github.com/Kitware/pan3d/assets/44912689/ae8b9dd0-124f-42b2-b4be-6aef0e5638a9

Edit: This PR also includes one semi-unrelated chage; the dataset I tested this feature on was incompatible with the type checking implemented in #70. I removed the check for numeric typing on the values in a slicing array, because we should allow strings for start and stop values of time axes.

### CODE REVIEW

**Review by johnkit — APPROVED** [review]
+2 Tested OK for me. This is a really nice feature - great work, Anne. 

I have one feature request, but we can merge this now if you prefer to consider that for a future PR:

When loading a new dataset in cartographic mode, it would be great if we adjusted the viewpoint to center and zoom on the dataset. Not so important for full-earth data, but a dataset covering a small area could be hard to find.

**Comment by johnkit** [comment]
I finally tested the March 29 updates today but I'm having problems.

1\. I seem to have a problem finding or reading the catalogs. For example, when I run `pan3d-viewer --catalogs pangeo esgf`, the viewer only lists the Xarray group.

2\. Stranger still, if I use `-c` instead of `--catalogs`, the viewer raises an exception

```
(test05-pan3d) john.tourtellott@turtleland5:~/projects/pan3d/git/pan3d$ pan3d-viewer -c pangeo 
Traceback (most recent call last):
  File "/home/local/KHQ/john.tourtellott/.py3-venv/test05-pan3d/lib/python3.9/site-packages/aiohttp/web_urldispatcher.py", line 561, in __init__
    raise ValueError("Not a directory")
ValueError: Not a directory
```

3\. This one is probably unrelated to this MR, and/or might be a dev thing, but just in case: The install[all] option is not installing the options, just the core packages. Here's the output copied from my terminal.

<details>
<summary>Terminal Log</summary>
<pre>
(test05-pan3d) john.tourtellott@turtleland5:~/projects/pan3d/git/pan3d$ pip install -e .[all]
Obtaining file:///home/local/KHQ/john.tourtellott/projects/pan3d/git/pan3d
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting zarr>=2.16
  Downloading zarr-2.17.2-py3-none-any.whl (208 kB)
     |████████████████████████████████| 208 kB 819 kB/s
Collecting pyvista>=0.43
  Downloading pyvista-0.43.5-py3-none-any.whl (1.9 MB)
     |████████████████████████████████| 1.9 MB 2.1 MB/s
Collecting requests>=2.31
  Using cached requests-2.31.0-py3-none-any.whl (62 kB)
Collecting dask>=2023.10
  Downloading dask-2024.4.1-py3-none-any.whl (1.2 MB)
     |████████████████████████████████| 1.2 MB 3.5 MB/s
Collecting xarray>=2023.8
  Downloading xarray-2024.3.0-py3-none-any.whl (1.1 MB)
     |████████████████████████████████| 1.1 MB 3.9 MB/s
Collecting aiohttp>=3.8
  Using cached aiohttp-3.9.3-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.2 MB)
Collecting pyvista-xarray>=0.1
  Using cached pyvista_xarray-0.1.5-py3-none-any.whl (17 kB)
Collecting fsspec>=2023.9
  Using cached fsspec-2024.3.1-py3-none-any.whl (171 kB)
Collecting netCDF4>=1.6
  Using cached netCDF4-1.6.5-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.5 MB)
Collecting fasteners; sys_platform != "emscripten"
  Using cached fasteners-0.19-py3-none-any.whl (18 kB)
Collecting numpy>=1.23
  Using cached numpy-1.26.4-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.2 MB)
Processing /home/local/KHQ/john.tourtellott/.cache/pip/wheels/07/00/bc/937e878be0d781a569792a1e0e5acf149e463d4536453ec978/asciitree-0.3.3-py3-none-any.whl
Collecting numcodecs>=0.10.0
  Using cached numcodecs-0.12.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (7.7 MB)
Collecting pooch
  Using cached pooch-1.8.1-py3-none-any.whl (62 kB)
Collecting matplotlib>=3.0.1
  Downloading matplotlib-3.8.4-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.6 MB)
     |████████████████████████████████| 11.6 MB 4.1 MB/s
Collecting vtk
  Using cached vtk-9.3.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (92.0 MB)
Collecting pillow
  Downloading pillow-10.3.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.4 MB)
     |████████████████████████████████| 4.4 MB 3.7 MB/s
Collecting scooby>=0.5.1
  Using cached scooby-0.9.2-py3-none-any.whl (18 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.6-py3-none-any.whl (61 kB)
Collecting urllib3<3,>=1.21.1
  Using cached urllib3-2.2.1-py3-none-any.whl (121 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2024.2.2-py3-none-any.whl (163 kB)
Collecting charset-normalizer<4,>=2
  Using cached charset_normalizer-3.3.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (142 kB)
Collecting partd>=1.2.0
  Using cached partd-1.4.1-py3-none-any.whl (18 kB)
Collecting pyyaml>=5.3.1
  Using cached PyYAML-6.0.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (738 kB)
Collecting toolz>=0.10.0
  Using cached toolz-0.12.1-py3-none-any.whl (56 kB)
Collecting importlib-metadata>=4.13.0; python_version < "3.12"
  Using cached importlib_metadata-7.1.0-py3-none-any.whl (24 kB)
Collecting click>=8.1
  Using cached click-8.1.7-py3-none-any.whl (97 kB)
Collecting packaging>=20.0
  Using cached packaging-24.0-py3-none-any.whl (53 kB)
Collecting cloudpickle>=1.5.0
  Using cached cloudpickle-3.0.0-py3-none-any.whl (20 kB)
Collecting pandas>=1.5
  Using cached pandas-2.2.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.0 MB)
Collecting frozenlist>=1.1.1
  Using cached frozenlist-1.4.1-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (240 kB)
Collecting multidict<7.0,>=4.5
  Using cached multidict-6.0.5-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (123 kB)
Collecting attrs>=17.3.0
  Using cached attrs-23.2.0-py3-none-any.whl (60 kB)
Collecting aiosignal>=1.1.2
  Using cached aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
Collecting async-timeout<5.0,>=4.0; python_version < "3.11"
  Using cached async_timeout-4.0.3-py3-none-any.whl (5.7 kB)
Collecting yarl<2.0,>=1.0
  Using cached yarl-1.9.4-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (304 kB)
Collecting cftime
  Using cached cftime-1.6.3-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.3 MB)
Collecting platformdirs>=2.5.0
  Using cached platformdirs-4.2.0-py3-none-any.whl (17 kB)
Collecting python-dateutil>=2.7
  Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
Collecting kiwisolver>=1.3.1
  Using cached kiwisolver-1.4.5-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.6 MB)
Collecting cycler>=0.10
  Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Collecting contourpy>=1.0.1
  Downloading contourpy-1.2.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (304 kB)
     |████████████████████████████████| 304 kB 3.5 MB/s
Collecting fonttools>=4.22.0
  Downloading fonttools-4.51.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.6 MB)
     |████████████████████████████████| 4.6 MB 4.8 MB/s
Collecting pyparsing>=2.3.1
  Using cached pyparsing-3.1.2-py3-none-any.whl (103 kB)
Collecting importlib-resources>=3.2.0; python_version < "3.10"
  Using cached importlib_resources-6.4.0-py3-none-any.whl (38 kB)
Collecting locket
  Using cached locket-1.0.0-py2.py3-none-any.whl (4.4 kB)
Collecting zipp>=0.5
  Using cached zipp-3.18.1-py3-none-any.whl (8.2 kB)
Collecting tzdata>=2022.7
  Using cached tzdata-2024.1-py2.py3-none-any.whl (345 kB)
Collecting pytz>=2020.1
  Using cached pytz-2024.1-py2.py3-none-any.whl (505 kB)
Collecting six>=1.5
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Installing collected packages: fasteners, numpy, asciitree, numcodecs, zarr, packaging, idna, urllib3, certifi, charset-normalizer, requests, platformdirs, pooch, six, python-dateutil, kiwisolver, pillow, cycler, contourpy, fonttools, pyparsing, zipp, importlib-resources, matplotlib, vtk, scooby, pyvista, toolz, locket, partd, pyyaml, importlib-metadata, fsspec, click, cloudpickle, dask, tzdata, pytz, pandas, xarray, frozenlist, multidict, attrs, aiosignal, async-timeout, yarl, aiohttp, pyvista-xarray, cftime, netCDF4, pan3d
  Running setup.py develop for pan3d
Successfully installed aiohttp-3.9.3 aiosignal-1.3.1 asciitree-0.3.3 async-timeout-4.0.3 attrs-23.2.0 certifi-2024.2.2 cftime-1.6.3 charset-normalizer-3.3.2 click-8.1.7 cloudpickle-3.0.0 contourpy-1.2.1 cycler-0.12.1 dask-2024.4.1 fasteners-0.19 fonttools-4.51.0 frozenlist-1.4.1 fsspec-2024.3.1 idna-3.6 importlib-metadata-7.1.0 importlib-resources-6.4.0 kiwisolver-1.4.5 locket-1.0.0 matplotlib-3.8.4 multidict-6.0.5 netCDF4-1.6.5 numcodecs-0.12.1 numpy-1.26.4 packaging-24.0 pan3d pandas-2.2.1 partd-1.4.1 pillow-10.3.0 platformdirs-4.2.0 pooch-1.8.1 pyparsing-3.1.2 python-dateutil-2.9.0.post0 pytz-2024.1 pyvista-0.43.5 pyvista-xarray-0.1.5 pyyaml-6.0.1 requests-2.31.0 scooby-0.9.2 six-1.16.0 toolz-0.12.1 tzdata-2024.1 urllib3-2.2.1 vtk-9.3.0 xarray-2024.3.0 yarl-1.9.4 zarr-2.17.2 zipp-3.18.1
(test05-pan3d) john.tourtellott@turtleland5:~/projects/pan3d/git/pan3d$ pan3d-viewer --catalogs pangeo esgf
Traceback (most recent call last):
  File "/home/local/KHQ/john.tourtellott/.py3-venv/test05-pan3d/bin/pan3d-viewer", line 33, in <module>
    sys.exit(load_entry_point('pan3d', 'console_scripts', 'pan3d-viewer')())
  File "/home/local/KHQ/john.tourtellott/projects/pan3d/git/pan3d/pan3d/serve_viewer.py", line 25, in serve
    builder.viewer.start(debug=args.debug)
  File "/home/local/KHQ/john.tourtellott/projects/pan3d/git/pan3d/pan3d/dataset_builder.py", line 58, in viewer
    from pan3d.dataset_viewer import DatasetViewer
  File "/home/local/KHQ/john.tourtellott/projects/pan3d/git/pan3d/pan3d/dataset_viewer.py", line 6, in <module>
    import geovista
ModuleNotFoundError: No module named 'geovista'

</pre>
</details>

**Comment by annehaley** [comment]
@johnkit Thanks for reporting these.

1. This is expected behavior; adding catalogs does not add them to the available data groups. It adds them to a list of available catalogs in the catalog search dialog. A non-empty list of available catalogs makes the "Search Catalogs" button visible and the dialog accessible. The search dialog allows you to add new data groups with your searches.
2. Ok, I hadn't tried using the `-c` flag version, so I hadn't caught that this conflicts with a trame flag for "--content". We should probably rename the flag version of "--catalogs". What do you think would be appropriate?
3. I'm not able to replicate this. When I create a new virtual environment with python 3.9 and run `pip install -e .[all]` in that environment, I get all the optional dependencies. Running `pip list` shows me that trame packages, intake packages, and geovista are installed. What version of python are you using in the environment where you attempt to install all? And were you on the `cartographic` branch when you did this?

**Review by jourdain — COMMENTED** [review]
Seems reasonable but now we are forced of using geovista instead of pyvista. Do we want that? Should we make it optional? Just wondering

**Comment by johnkit** [comment]
> Seems reasonable but now we are forced of using geovista instead of pyvista. Do we want that? Should we make it optional? Just wondering

Anne and I talked about making geovista an option. Given its relatively small package size (100KB), I think it's OK to just include in the viewer option. (pyvista is still loaded too, of course.)

**Pull request merged**
